# Our Custom Resource Definition for a DaemonsTool
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: daemonstools.ualter.com
spec:
  group: ualter.com
  version: v1beta1
  names:
    kind: Daemonstool
    plural: daemonstools
    singular: daemonstool
    shortNames:
      - dt
  # either Namespaced or Cluster  
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            label:
              type: string
            image:
              type: string
            key:
              type: string
              minimum: 1  
          required:
            - image
            - key